Feature/shortcut task navigation
Project-OSmOSE/osmose-app pull request #126
Opened 2023-10-18 13:27 UTC by Qouagga

#15

2023-10-25 09:33 UTC, rvovard requested changes
Mostly OK, just a few changes.

2023-10-25 09:33 UTC, rvovard commented on frontend/src/AudioAnnotator/AudioAnnotator.js
> +              <Link className="btn btn-submit rounded-left rounded-right-0" disabled={this.state.task.prevAndNextAnnotation.prev === "" ? true : false} to={this.state.task.prevAndNextAnnotation.prev
We don't need a ternary operator here : `this.state.task.prevAndNextAnnotation.prev === "" ? true : false`, the condition alone returns true or false.
And, just to improve readability, perhaps put each attribute on a new line?

2023-10-25 09:33 UTC, rvovard commented on frontend/src/AudioAnnotator/AudioAnnotator.js
> +              <Link className="btn btn-submit rounded-right rounded-left-0" disabled={this.state.task.prevAndNextAnnotation.next === "" ? true : false}
Same as above:
We don't need a ternary operator here : `this.state.task.prevAndNextAnnotation.next === "" ? true : false`, the condition alone returns true or false.
And, just to improve readability, perhaps put each attribute on a new line?

2023-10-25 16:13 UTC, rvovard approved these changes
OK, thanks for the changes

2023-11-08 16:37 UTC, rvovard reviewed
This PR contains most of the content of PR #131
I've tried to review only the changes of this PR using [this view](https://github.com/Project-OSmOSE/osmose-app/compare/feature/campaign-date-created..feature/Shortcut-task-navigation). The code seems good. Asking for a little "cosmetic" change.

I think it's best to merge #131 first, then to check again if this PR works.

2023-11-08 16:37 UTC, rvovard commented on frontend/src/utils.js
> +}
Just a typo: please keep a new line at the end of the files.
It's a good practice as it can help with command line tools.

2023-11-20 17:07 UTC, ixio requested changes
I'm not sure about making the sorting in JS, unsure both about the principle and this implementation.

For the principle I think it'd be much shorter and simpler to specify the default order in the backend : you only need to set it once and then you have a nice default order everywhere, only when the front needs a different order you can add some code.

On the implementation : with your changes to `arrayToObject` you are changing the keys of the object from id1, id2, id3, etc... to 1, 2 ,3, etc... : are you sure you haven't forgotten to update some place where we try to access via key ? I've tested your branch on staging and when adding/removing many annotators I get an error. Not sure the exact steps to reproduce but it seems pretty easy to trigger (be sure to check the right branch in private navigation). Also it seems that the selected username isn't the one added in the end (probably a difference in order).

2023-11-22 14:54 UTC, ixio approved these changes

2023-11-22 14:56 UTC, merged